### ISSUE TITLE
Demo on iOS

### ISSUE THREAD

**Issue by NathanWalker** [SekibOmazic/angular2-playground#2]
Should this work on mobile safari?
Right now it does not.

**Comment by SekibOmazic** [comment]
Atm it doesn't work on Safari. Only tried desktop though. Need to investigate why.

**Comment by SekibOmazic** [comment]
The problem has been fixed with https://github.com/angular/angular/issues/1640 but it didn't make it in alpha.23. So we need to wait for the next Angular release.
